
a : b\
	 c 			 \
	  	d 			\
		e
	echo a
b:
	echo asfasdfasfsf\
	fdsfdsfsdsdfsdf
c:
	echo asfasdfasfsf\
	fdsfdsfsdsdfsdf
d:
	echo asfasdfasfsf\
	fdsfdsfsdsdfsdf
e:
	echo asfasdfasfsf\
	fdsfdsfsdsdfsdf\
	sfsdf\
	sfsd\
	fsdfdssd\
	fsdf
