#comment #comment #comment #comment #comment #comment
#comment #comment #comment #comment #comment #comment
#comment #comment #comment #comment #comment #comment
#comment #comment #comment #comment #comment #comment
#comment #comment #comment #comment #comment #comment
#comment
a : b #comment
	echo a #comment
#comment #comment #comment #comment #comment #comment
b : c #fdflsdkfjdsfl
	echo b #comment #comment #comment #comment #comment #comment
#comment #comment #comment #comment #comment #comment
#comment #comment #comment #comment #comment #comment
#comment #comment #comment #comment #comment #comment
#comment #comment #comment #comment #comment #comment
#comment #comment #comment #comment #comment #comment
#comment #comment #comment #comment #comment #comment
c:
