a = b
b = c
c := c
g$($($($($(c)))))$($($(c))) = g$(c)$g$(c)
c ?= a
c ?=
c ?=

all$(targets)$()$($($()))$(c)ff$(WWc)$(c) : $(c)
	echo "$($($(g$(c$(c$(c)$(c)))))) -o $<.o -Wall $@ && echo $@ $<$<$<"

c: ;echo $(c)
